name: Build and Release Calamares

on:
  push:
    branches:
      - main
  #schedule:
  #  - cron: '0 0 * * *'  # Schedule to run every day at 12 AM UTC

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      pull-requests: write
      repository-projects: write
    container:
      image: archlinux/archlinux:latest
      options: --privileged

    steps:
      - name: Checkout repository using git
        run: |
          pacman -Sy git sudo base-devel cmake github-cli --noconfirm
          sudo pacman -S extra-cmake-modules yaml-cpp boost qt5-base qt5-declarative \
               hwinfo python-jsonschema python-yaml solid squashfs-tools
               qt5-quickcontrols2 qt5-svg qt5-tools qt5-translations qt5-webengine libpwquality libyaml \
               kpmcore kcoreaddons ki18n kconfig kservice kwidgetsaddons kiconthemes kitemviews kxmlgui \
               kbookmarks kcompletion --needed --noconfirm

      - name: Install dependencies for makepkg
        run: |
          sudo pacman -S --needed --noconfirm fakeroot

      - name: Create dummy user for makepkg
        run: |
          sudo useradd -m builder -s /bin/bash
          sudo usermod -aG wheel builder
          sudo echo '%wheel ALL=(ALL) NOPASSWD:ALL' | sudo tee -a /etc/sudoers
          
      - name: Install ckbcomp
        run: |
          git clone https://aur.archlinux.org/ckbcomp.git
          sudo chmod -R 777 ./ckbcomp.git
          cd ckbcomp-git
          sudo -u builder makepkg -si --noconfirm

      - name: Build Calamares on Arch Linux
        run: |
          git clone https://aur.archlinux.org/calamares-git
          sudo chmod -R 777 $BUILDDIR ./calamares-git
          cd calamares-git
          sed -i 's/3\.3\.5\(-[^ ]*\)/3.7-git/' PKGBUILD
          sudo -u builder makepkg -fcs --noconfirm

      - name: Release artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release
          mv *.pkg.tar.zst release/
          cd release
          for file in *.pkg.tar.zst; do
            echo "Uploading $file to releases"
            gh release upload $GITHUB_REPOSITORY@$GITHUB_RUN_ID "$file"
          done
